export const RETURN_REQUEST_STATUSES = {
  RETURN_PENDING: "RETURN_PENDING",
  RETURN_APPROVED: "RETURN_APPROVED",
  RETURN_REJECTED: "RETURN_REJECTED",
  ITEM_RECEIVED: "ITEM_RECEIVED",
  RETURN_COMPLETED: "RETURN_COMPLETED",
};
