export const ORDER_STATUS_TRANSITIONS = {
  PLACED: ["PROCESSING", "CANCELLED"],

  PROCESSING: ["SHIPPED", "CANCELLED"],

  SHIPPED: ["OUT_FOR_DELIVERY"],

  OUT_FOR_DELIVERY: ["DELIVERED"],

  DELIVERED: [],

  CANCELLED: [],
};

export const ITEM_STATUS_TRANSITIONS = {
  PLACED: ["PROCESSING", "CANCELLED"],

  PROCESSING: ["SHIPPED", "CANCELLED"],

  SHIPPED: ["OUT_FOR_DELIVERY"],

  OUT_FOR_DELIVERY: ["DELIVERED"],

  DELIVERED: [],

  CANCELLED: [],

  RETURN_PENDING: ["RETURN_APPROVED", "RETURN_REJECTED"],

  RETURN_APPROVED: ["ITEM_RECEIVED"],

  ITEM_RECEIVED: ["RETURN_COMPLETED"],

  RETURN_COMPLETED: [],

  RETURN_REJECTED: [],
};